on: [push]

jobs:
  aarch64_job:
    runs-on: ubuntu-latest
    name: Build sarchile base system image
    steps:
      - uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@v2.1.1
        name: Running build commands
        with:
          arch: aarch64
          distro: ubuntu20.04
          githubToken: ${{ github.token }}
          run: |
            sudo docker import http://os.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz archarm:latest
            sudo docker build . --file Dockerfile --tag base:$(date +%s)
            sudo docker save sarchile | gzip > sarchile.tar.gz
            
      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "base"
          draft: true
          prerelease: true
          title: "Base system image"
          files: |
            sarchile.tar.gz
