name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Call docker to fetch latest archlinuxarm image
      run: sudo docker import http://os.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz archarm:latest

    - name: Build the image
      run: sudo docker build . --file Dockerfile.aarch64 --tag base:$(date +%s)
    
    - name: Save and export built image
      run: sudo docker save sarchile | gzip > sarchile.tar.gz
    
    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "base"
        draft: true
        prerelease: true
        title: "Base system image"
        files: |
          sarchile.tar.gz
