name: Docker Image CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_TARGET_PLATFORM: linux/arm64
    steps:
    - name: Checkout latest code
      uses: actions/checkout@v2
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1.2.0
      with:
        platforms: linux/arm64
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.6.0

    - name: Call docker to fetch latest archlinuxarm image
      run: sudo docker import http://os.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz archarm:latest

    - name: Build the image
      run: sudo docker build . --file Dockerfile --tag base:latest
    
    - name: DEBUG Print available images
      run: sudo docker ps

    #- name: Save and export built image
    #  run: sudo docker save -o ./base.tar.gz base:latest
    
    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "base"
        draft: true
        prerelease: true
        title: "Base system image"
        files: |
          base.tar.gz
